/* IMBHeader:  1.0.0
 * Programa:   help.h 
 * Directorio: xescoba-1.2.1/src 
 * Fecha:      Sun Apr 15 16:42:49 CEST 2001 
 * Autor:      Ignacio Mart�n Bragado.
 * e-mail:     ignacio.martin@tel.uva.es 
 * M�quina:    Linux 
 */

/***************************************************************************
 Improving this program will be thanked. You can do it in author address:
 ignacio.martin@tel.uva.es
 ******************************************************************************/              

/*############################################################################
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#############################################################################*/

const char *HelpStrEn = 
"----------------------------------------------------------------------------\n"
"1.- What is xescoba?\n"
"----------------------------------------------------------------------------\n"
"\n"
"xescoba is an 'escoba' (broom, sweeping) playing program. The escoba \n"
"game is a popular Spanish cards game.\n"
"\n"
"----------------------------------------------------------------------------\n"
"1.1- What are 'escoba' rules?\n"
"----------------------------------------------------------------------------\n"
"\n"
"	The 'escoba' purpose is to win the greatest possible amount of cards,\n"
"golds, sevens, sweepings and the special card named the 'velo', that is, the\n"
"seven of golds. Every sweeping and the 'velo' wins one point. For the rest\n"
"the point is won when you have more amount of golds, cards or sevens than\n"
"the others.\n"
"\n"
"	You make a 'escoba' or a sweeping when you win all the cards on the\n"
"center.\n"
"\n"
"	Playing 'escoba' is simple: You have only to play a card every turn.\n"
"If there is some combination of this card with centers ones adding 15 you\n"
"win this cards. If not your card stays on center. In order to make this\n"
"combination you should know that knights are 9 points, kings 10 and 'sotas'\n"
"8 points. That is. The cards whose nominal value are 1,2,3,4,5,6 and 7 are\n"
"evaluated as 1,2,3,4,5,6 and 7 (no difficult!) and the 10,11 and 12 as 8,9\n"
"and 10. Here is a table:\n"
"\n"
"	Nominal value.		Real value for adding\n"
"	1				1\n"
"	2				2\n"
"	3				3\n"
"	4				4\n"
"	5				5\n"
"	6				6\n"
"	7				7\n"
"	10 (sota)			8\n"
"	11 (knight)			9\n"
"	12 (king) 			10\n"
"\n"
"	For example: Playing a seven with a 'sota' is a valid trick, because\n"
"they add 15. \n"
"	More examples: Here are some examples. NOTE: There are a lot of\n"
"more valid tricks then the ones here!.\n"
"	Real cards			Values for adding  \n"
"\n"
"	1,4,king			1+4+10 = 15  	OK!\n"
"	2,2,2,knight			2+2+2+9=15	OK!\n"
"	7+sota				7+8=15		OK!\n"
"	4,5,6				4+5+6=15	OK!\n"
"	1,1,3,7,3			1+1+3+7+3=15	OK! 	\n"
"	\n"
"----------------------------------------------------------------------------\n"
"2.- What are xescoba options?\n"
"----------------------------------------------------------------------------\n"
"\n"
"----------------------------------------------------------------------------\n"
"2.1.- In menu\n"
"----------------------------------------------------------------------------\n"
"\n"
"	In the properties option of menu you can chose:\n"
"\n"
"	Sound	\n"
"		Make sound active or not.\n"
"	Game exposition window\n"
"		To active or not the visualization of last trick.\n"
"	Advice	\n"
"		When advice is active the computer select for you what it\n"
"		think is the better trick. If you accept it only have to\n"
"		click in turn button. Else you should reselect your trick\n"
"		and clicking turn button.\n"
"	Configuration\n"
"		When selecting configuration you obtain a configuration\n"
"		dialog. Here you can select the number of players (from 2 to\n"
"		4) and their nature (human or computer ones). You can write\n"
"		their names, too.\n"
"		This dialog modifies the configuration file. (Further\n"
"		information in 2.2) \n"
"\n"
"----------------------------------------------------------------------------\n"
"2.2.- The configuration file.\n"
"----------------------------------------------------------------------------\n"
"\n"
"	The configuration file .xescoba should be in $HOME. Such file have\n"
"the following fields:\n"
"\n"
"	jugadores = players_number\n"
"\n"
"		players_number is a number from 1 to 4\n"
"\n"
"	jugador0 = player_name0\n"
"	jugador1 = player_name1\n"
"	jugador2 = player_name2\n"
"	jugador3 = player_name3\n"
"	naturaleza0 = 0_or_1\n"
"	naturaleza1 = 0_or_1\n"
"	naturaleza2 = 0_or_1\n"
"	naturaleza3 = 0_or_1\n"
"\n"
"	For a human player you write:\n"
"		naturalezaX = 0\n"
"	where 'X' is a 0,1,2,3 according with the other fields. For a\n"
"	computer one you write \n"
"		naturalezaX = 1\n"
"\n"
"----------------------------------------------------------------------------\n"
"3.- Distribution license.\n"
"----------------------------------------------------------------------------\n"
"\n"
"	GPL. For further information see COPYING.\n"
"\n"
"----------------------------------------------------------------------------\n"
"3.1.- About cards pixmaps.\n"
"----------------------------------------------------------------------------\n"
"\n"
"\n"
"	Cards pixmaps have been made by xescoba author, using lots of\n"
"imagination, the excellent GIMP program and his poor artistic talent.\n"
"\n"
"	The Linux logo, created by Larry Ewing, has been used too.\n"
"\n"
"	The license for distributing this pixmaps are GPL (or LGPL).  \n"
"\n"
"----------------------------------------------------------------------------\n"
"4.- Additional license\n"
"----------------------------------------------------------------------------\n"
"\n"
"	Here is the license for the linux logo. (The original files are in\n"
"	linux kernel)\n"
"\n"
"logo.txt:\n"
"\n"
"	 This is the full-colour version of the currently unofficial Linux logo\n"
"	('currently unofficial' just means that there has been no paperwork and\n"
"	that I haven't really announced it yet).  It was created by Larry Ewing,\n"
"	and is freely usable as long as you acknowledge Larry as the original\n"
"	artist.\n"
"\n"
"	Note that there are black-and-white versions of this available that\n"
"	scale down to smaller sizes and are better for letterheads or whatever\n"
"	you want to use it for: for the full range of logos take a look at\n"
"	Larry's web-page:\n"
"\n"
"        	http://www.isc.tamu.edu/~lewing/linux/\n"
"\n"
"\n"
"						The end.\n";

const char *HelpStrEs = 
"----------------------------------------------------------------------------\n"
"1.- �Qu� es xescoba?\n"
"----------------------------------------------------------------------------\n"
"\n"
"	Xescoba es una implementaci�n en GTK del popular juego espa�ol de la\n"
"escoba.\n"
"\n"
"----------------------------------------------------------------------------\n"
"1.1- �Cu�les son las reglas de la escoba?\n"
"----------------------------------------------------------------------------\n"
"\n"
"	El objetivo de la escoba es llevarse el mayor n�mero posible de\n"
"cartas, oros, escobas, sietes y el siete de oros. Cada escoba, as� como el\n"
"velo (el siete de oros) vale un punto. Para el resto se lleva un punto el\n"
"que m�s cantidad haya logrado llevarse. \n"
"	Se produce 'una escoba' cuando un jugador logra llevarse todas las\n"
"cartas que hay en el centro.\n"
"	Para jugar hay que tirar siempre una carta. Si existe alguna\n"
"combinaci�n de esa carta con las que hay en el centro tal que sumen quince,\n"
"considerando que las sotas valen 8, los caballos 9 y los reyes 10, y el\n"
"resto de las cartas su puntuaci�n nominal, el jugador recoge las cartas que\n"
"le sumen 15 y las pone en su baza. Por ejemplo, una sota y un siete 'suman\n"
"quince' y, por tanto, es una baza v�lida.\n"
"\n"
"----------------------------------------------------------------------------\n"
"2.- �Qu� opciones tiene xescoba?\n"
"----------------------------------------------------------------------------\n"
"\n"
"----------------------------------------------------------------------------\n"
"2.1.- En el men�.\n"
"----------------------------------------------------------------------------\n"
"\n"
"	En el men� propiedades se puede elegir:\n"
"\n"
"	Sonido-> Activa/desactiva el sonido.\n"
"	Ver cartas->Activa/Desactiva el panel para ver la �ltima jugada.\n"
"	Sugerencias->Cuando est� activado el ordenador selecciona para un\n"
"		jugador 'humano' lo que �l considera la mejor jugada.\n"
"		El jugador humano puede aceptarla o bien seleccionar la\n"
"		jugada que quiera. Esta selecci�n se hace de forma que la\n"
"		mejor jugada (seg�n el criterio del ordenador) aparecer� ya\n"
"		cogida tanto en las cartas del centro como en las del\n"
"		jugador. Esto es, basta dar al bot�n de turno si se acepta\n"
"		la jugada, porque estar�n las cartas seleccionadas.\n"
"	Configuraci�n -> Permite decir cuantos van a ser los jugadores en \n"
"		la pr�xima partida, y si van a tratarse de jugadores\n"
"		regulados por el ordenador o bien ser�n humanos. Tambi�n se\n"
"		puede poner el nombre de los jugadores en el cuadrado\n"
"		correspondiente. Para seleccionar el n�mero de jugadores y\n"
"		su naturaleza basta con pinchar en el bot�n adecuado. Para\n"
"		cambiar los nombres hay que escribir en el cuadro de nombre\n"
"		correspondiente.\n"
"			Este di�logo lo que hace es modificar el fichero de\n"
"		configuraci�n para la pr�xima partida. (Ver en 2.2).\n"
"\n"
"----------------------------------------------------------------------------\n"
"2.2.- En el fichero de configuraci�n.\n"
"----------------------------------------------------------------------------\n"
"\n"
"	El fichero de configuraci�n .xescoba deber�a encontrarse en la base\n"
"de tu directorio personal. Dicho fichero admite los siguientes\n"
"campos:\n"
"	jugadores = numero_jugadores\n"
"\n"
"	Donde numero_jugadores es un entero del 2 al 4.\n"
"\n"
"	jugador0 = Nombre0\n"
"	jugador1 = Nombre1\n"
"	jugador2 = Nombre2\n"
"	jugador3 = Nombre3\n"
"	naturaleza0 = 0_o_1\n"
"	naturaleza1 = 0_o_1\n"
"	naturaleza2 = 0_o_1\n"
"	naturaleza3 = 0_o_1\n"
"\n"
"	Se escriben los nombres de los cuatro jugadores (m�ximo) as� como\n"
"sus naturalezas. Para un jugador humano se pondr� 'naturalezaX = 0' siendo X\n"
"el n�mero del 0 al 3 que representa a este jugador. Para uno autom�tico, es\n"
"decir, para que lo lleve el ordenador, se pondr� 'naturalezaX = 1'.\n"
"\n"
"----------------------------------------------------------------------------\n"
"3.- �Bajo qu� licencia se distribuye xescoba?\n"
"----------------------------------------------------------------------------\n"
"\n"
"	Bajo licencia GPL. Para m�s informaci�n lee el fichero COPYING o\n"
"bien la cabecera de este documento.\n"
"	B�sicamente: No tienes que pagar para usar este programa, pero has\n"
"de respetar su copyright. Los t�rminos exactos se encuentran en el fichero\n"
"COPYING.\n"
"\n"
"----------------------------------------------------------------------------\n"
"3.1.- �De d�nde han salido esos dibujos de las cartas?\n"
"----------------------------------------------------------------------------\n"
"\n"
"	Los dibujos de las cartas han sido �ntegramente realizados por el\n"
"autor de xescoba y tambi�n se distribuyen con licencia GPL (o, si se\n"
"quisieran usar como librer�a, bajo LGPL). Les he hecho usando la\n"
"imaginaci�n, el programa GIMP y mis penosas dotes art�sticas. No obstante\n"
"tambi�n he usado el logotipo de linux, creado por Larry Ewing, para ponerle\n"
"de relieve en los oros. Incluyo m�s abajo la licencia de distribuci�n de\n"
"dicho fichero.\n"
" \n"
"----------------------------------------------------------------------------\n"
"4.- Licencias adicionales.\n"
"----------------------------------------------------------------------------\n"
"\n"
"	Tal y como se ha indicado en 3.1 he tomado para la creaci�n del\n"
"relieven en los oros el fichero logo.jpg que se distribuye con el n�cleo linux.\n"
"No obstante incluyo aqu� su licencia de utilizaci�n respectiva:\n"
"\n"
"logo.txt:\n"
"\n"
"	 This is the full-colour version of the currently unofficial Linux logo\n"
"	('currently unofficial' just means that there has been no paperwork and\n"
"	that I haven't really announced it yet).  It was created by Larry Ewing,\n"
"	and is freely usable as long as you acknowledge Larry as the original\n"
"	artist.\n"
"\n"
"	Note that there are black-and-white versions of this available that\n"
"	scale down to smaller sizes and are better for letterheads or whatever\n"
"	you want to use it for: for the full range of logos take a look at\n"
"	Larry's web-page:\n"
"\n"
"       	http://www.isc.tamu.edu/~lewing/linux/\n";
